# Generated by Django 2.2.5 on 2019-10-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('father_name', models.CharField(blank=True, max_length=300, null=True)),
                ('group', models.CharField(blank=True, max_length=300, null=True)),
                ('hos', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.CharField(blank=True, max_length=300, null=True)),
                ('mobile', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
